name: api-cookbook-dev
channels:
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - geopandas
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - pip
  - hvplot
  - cartopy
  - xarray
  - earthaccess
  - h5netcdf
  - dask
  - pip:
      - git+https://github.com/USEPA/pyaqsapi.git
